FROM node:22-slim

WORKDIR /app

COPY package*.json ./
COPY vite.config.ts ./

RUN npm install -D vite-tsconfig-paths @types/node
RUN npm install


CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]

