FROM python:3.12-slim

WORKDIR /app

RUN mkdir -p /tmp && chmod 777 /tmp

RUN pip install semgrep

COPY requirements.txt .

RUN pip install -r requirements.txt

CMD ["fastapi", "dev", "--host", "0.0.0.0"]
