FROM python:3.12-slim
COPY requirements.txt .
RUN pip install -r requirements.txt
RUN pip install fastapi-cli
WORKDIR /app
COPY ./src .
# CMD ["uvicorn", "main:app", "--host", "0.0.0.0"]
CMD ["fastapi", "dev", "--host", "0.0.0.0"]
