FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    curl \
    git \
    unzip \
    php \
    php-xml \
    php-dom \
    php-zip \
    && rm -rf /var/lib/apt/lists/*

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN composer global require phpstan/phpstan

RUN pip install semgrep==1.106.0

COPY requirements.txt .

RUN pip install -r requirements.txt

CMD ["python3", "src/worker_dev.py"]
